[package]
name = "pinewood_diesel"
version = "0.1.0"
authors = ["Nick Stockton <sputnick1124@comcast.net>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
